version: 2

updates:
  - package-ecosystem: pip
    directory: '/'
    schedule:
      interval: weekly
    ignore:
      - dependency-name: '*'
        update-types: ['version-update:semver-patch']
    reviewers: [stinodego]
    assignees: [stinodego]

  - package-ecosystem: github-actions
    directory: '/'
    schedule:
      interval: weekly
    reviewers: [stinodego]
    assignees: [stinodego]
